### ISSUE TITLE
`rtx implode`

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#147]
To make it a bit easier to uninstall, we could have an “implode” command that deletes the rtx binary, installs, plug-ins, and cache

**Comment by aniravi24** [comment]
It would be cool to have the ability to clean up everything except the binary (like a clean install), especially for those that install rtx via package manager.

Also instead of `implode`, `destroy` might be a better name.

Not to overload with options, but I imagine commands like:

`rtx destroy cache`
`rtx destroy workspace`
`rtx destroy all`
