### ISSUE TITLE
dockerize dev setup

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#169]
Contributing to rtx is a bit painful. The E2E and unit tests can be impacted by the local environment. If you have `rtx activate` set, it will almost certainly do the wrong thing.

Rather than continue to try sandboxing everything, I feel like it would be better to do our development inside of a docker container. This will make it easier for contributors since it will have dependencies like direnv and fish already setup.

Ironically I haven't been able to use rtx myself yet for its intended purpose. I'm always resetting my environment and testing edge cases so it's basically always in a bad state. If I had this I might be able to actually use it myself.

**Comment by blopker** [comment]
If it's helpful, I took a stab at making a Dockerfile for this.

Dockerfile:
```
FROM rust
RUN cargo install just
ENV CARGO_TARGET_DIR=/target
WORKDIR /app
CMD ["bash", "-c", "just", "test" ]
```

Build with: `docker build -t rtx-test .`
Run with: `docker run -it -v $PWD:/app rtx-test`

The full run takes about 1 minute on my machine (M1 Max). If people are going to develop and want a fast cycle time, they can shell into the container and run `just test`, this will allow for incremental builds. That takes about 9 seconds for me. On the host it takes around 3 seconds, although maybe adding more resources to Docker will help. I'd guess on Linux there wouldn't be as big of a performance hit, but I'm not that cool 😢. 

The Dockerfile keeps the `target` directory outside the `/app` mount to make the build as fast as possible. Otherwise, incremental builds take about 30 seconds.

Example for developing: `docker run -it -v $PWD:/app rtx-test bash`, then `just make` inside the container after a change is made.

Anyway, there's one failing test with this setup:
```
failures:

---- cli::direnv::exec::tests::test_direnv_exec stdout ----
thread 'cli::direnv::exec::tests::test_direnv_exec' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)

Location:
    src/cli/direnv/exec.rs:38:20', src/cli/direnv/exec.rs:66:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm not sure what the issue is though, potentially the Dockerfile is missing a dependency.

**Comment by jdxcode** [comment]
that error message is pretty bad, I think this is happening because direnv isn't installed.

btw @roele was working on this today as well, see #258

**Comment by blopker** [comment]
Ah! Nice. I don't use VS Code containers so that's why I took this approach. I'll let them take it from here then.

**Comment by blopker** [comment]
Ok, I actually played with it a little more. I was able to get much farther with this Dockerfile:

```
FROM ubuntu
RUN apt-get update && \
    apt-get install -y curl git direnv shfmt shellcheck build-essential zsh nodejs software-properties-common && \
    apt-add-repository ppa:fish-shell/release-3 && \
    apt-get update && \
    apt-get install -y fish && \
    rm -rf /var/lib/apt/lists/* && apt-get clean
RUN curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup component add clippy rustfmt
RUN cargo install just
ENV CARGO_TARGET_DIR=/target
ENV PATH="/target/debug/:${PATH}"
WORKDIR /app
CMD ["bash", "-c", "just", "test" ]
```
It's stuck on the e2e tests now. The `find` command on my machine finds the test scripts in a different order than on Github Actions, so that could be an issue. It seems like the problem is that the command `rtx shell nodejs@16.0.0` becomes interactive for some reason.

**Comment by jdxcode** [comment]
Can we pipe the tests through sort to run them alphabetically?

**Comment by jdxcode** [comment]
@blopker the builds we're failing in CI, but started working again on retry. I think GitHub's API was failing. You might want to just try again.

**Comment by blopker** [comment]
I did try to order the tests in the same way Github runs them, but the same errors still happen:

```
Running e2e/cd/test_zsh
[WARN] nodejs@18.0.0 already installed
[WARN] nodejs@16.0.0 already installed
rtx nodejs@18.0.0 jq@1.6 shellcheck@0.9.0 shfmt@3.6.0
rtx nodejs@16.0.0 jq@1.6 shellcheck@0.9.0 shfmt@3.6.0
rtx nodejs@18.0.0 jq@1.6 shellcheck@0.9.0 shfmt@3.6.0
error: Recipe `test-e2e` failed on line 33 with exit code 1
```

That line is calling `rtx shell nodejs@16.0.0`. When I run that in the Docker shell, I get an interactive prompt:

```
root@9cbdea0280f0:/app# rtx shell nodejs@16.0.0
? Select versions to install ›
✔ nodejs@16.0.0
✔ tiny@1
✔ golang@latest
✔ shellcheck@0.9.0
✔ shfmt@3.6.0
✔ jq@latest
```
What's supposed to happen?

**Comment by jdxcode** [comment]
the e2e tests are set to [autoinstall](https://github.com/jdxcode/rtx/blob/main/e2e/run_test#L7), not prompt.

**Comment by blopker** [comment]
Right now I'm seeing the error above happen intermittently, even when just running the single `cd/test_zsh` test. Half the time it passes, half the time it fails. It's hard to diagnose, but I'm guessing it has to do with Docker and the way the volume mounts work.  Maybe writes aren't getting flushed fast enough? Maybe `rtx` is _too_ fast :)

**Comment by jdxcode** [comment]
now that you mention it, I've seen an occasional bug on CI that this reminds me of. The install scripts very occasionally will fail for an inexplicable reason. Here is one: https://github.com/jdxcode/rtx/actions/runs/4298562429/jobs/7492804879

There is no reason I can think of why it wouldn't be able to access that file. My only guess is it's a race condition with something else that is trying to delete that file but I have no idea what it would be.

This I've never seen in E2E tests though, only unit tests.
