### ISSUE TITLE
Rust install doesn't perform a complete installation

### ISSUE THREAD

**Issue by pedropombeiro** [jdxcode/rtx#19]
I'm trying to convert from asdf to rtx on my QNAP NAS, and I noticed that doing `rtx global rust@1.58.1` and then `source "$HOME/.local/share/rtx/installs/rust/1.58.1/env"` doesn't result in a working rust install. I still needed to perform `rustup default 1.58.1` (would be easier to script if there was an `rtx`command that returns the currently configured rust version). 

Is this known? I don't recall having to call `rustup` with asdf.

**Comment by jdxcode** [comment]
Frankly I'm not actually sure that it makes much sense to use asdf or rtx with rust since rustup has its own method of managing the rust version with cargo. I think this is one language that's best left to the idiomatic tools.

That said, rtx should definitely do what it can here. I'll have to dig into the rust plugin and see how it's meant to work.

**Comment by pedropombeiro** [comment]
I made a second attempt to convert my environment to rtx, and didn't come across this problem the second time. I also decided to use `rustup` instead of leveraging rtx/asdf for it since that allows me to use a recent rust version on a Linux distro that I run that has an older glibc version, so I'm closing this bug report. Thanks for your insights!

**Comment by jdxcode** [comment]
I haven't yet had the time to look into this but this plugin uses the exec-env which I've fixed several issues around since you posted this. I suspect it's probably working now but will eventually get around to testing this.

**Comment by jdxcode** [comment]
this appears to be working fine now
