### ISSUE TITLE
asdf-java incompatibilities

### ISSUE THREAD

**Issue by blopker** [jdxcode/rtx#2]
There seems to be 2 (non-critical?) errors thrown with the Java plugin when installing a new Java version:

```
❯ rtx install java@openjdk-19.0.2
rtx: Installing runtime: java@openjdk-19.0.2
/Users/blopker/.local/share/rtx/plugins/java/bin/install: line 3: /Users/blopker/.asdf/lib/utils.bash: No such file or directory
######################################################################################################## 100.0%
openjdk-19.0.2_macos-aarch64_bin.tar.gz
openjdk-19.0.2_macos-aarch64_bin.tar.gz: OK
/Users/blopker/.local/share/rtx/plugins/java/bin/install: line 139: get_asdf_config_value: command not found
```

It seems to install fine though, not sure if it's worth investigating.

Also, `rtx install java` does not work. Not sure if it should though.

**Comment by jdxcode** [comment]
I can dig into this more tomorrow. It's likely just that I'm missing some environment variable that asdf sets.

> Also, rtx install java does not work

This is actually an issue with the plugin (arguably). It doesn't output any "normal" versions that start with a number. It's an issue in asdf as well:

```
❯ asdf latest java
No compatible versions available (java [0-9])
```

I'm not sure what _should_ happen here but it likely needs to be fixed in the java plugin. One thought I had is maybe it should use the [`bin/latest-stable`](https://asdf-vm.com/plugins/create.html#optional-scripts) script. Currently rtx doesn't use that since I couldn't find a plugin that used it as a reference.

**Comment by jdxcode** [comment]
oh, [reading the code](https://github.com/halcyon/asdf-java/blob/master/bin/functions), it actually is importing some asdf source code. That obviously isn't there since asdf isn't installed. If you installed asdf (just didn't add it to your shell rc) that _should_ fix it.

We may need a longer term solution here though, especially if this is something happening in other plugins.

**Comment by blopker** [comment]
Cool, yeah, not a blocker at all, just thought I'd surface it in case another plugin does break. I think the Java plugin (and to an extent Java) is just weird. I'd say it should default to openjdk, but I'm sure people would argue otherwise. 

I'm never installing asdf again! 😛

**Comment by jdxcode** [comment]
I explain this in the readme but the java plugin is actually probably the best suited to rtx over asdf. You don't need to setup the special asdf-java shell extension to get `JAVA_HOME` to work, it'll just set `JAVA_HOME` automatically the way you expect.

**Comment by jdxcode** [comment]
though, that's a theory, I'm not a java dev so maybe you can tell me how well it actually works :)

**Comment by blopker** [comment]
As far as I know, `JAVA_HOME` is not for the executable, but largely used by other tooling to find the Java SDK. Typically, IDEs will use it to fine the right source files to import. Although since IDEs usually configure that themselves I've never had an issue with asdf not setting it properly.

**Comment by jdxcode** [comment]
I did test java somewhat and it seems to work reasonably well. It does throw this error but it isn't important. There is also the matter of there not being a default version.

I think barring some rough solutions these both rely on changes within the plugin, or perhaps forking the java plugin into an RTX variant so that's the one that gets picked up when you run `rtx install java`

That said, there are a ton of other issues people have raised that I feel are more important so this one has dropped near the bottom of my queue. I'd be happy to consider any solutions here, or if the problems are bigger than I see let me know.

I'll keep this open of course, I just figured I'd let you know I don't think it's super likely I'll get around to this in the near term.

**Comment by blopker** [comment]
Thanks for the follow up! I'm not blocked or really effected by this. Thanks for making sure it's not a big issue.

I'm good with this outcome, I have know problem if you want to close it.

**Comment by roele** [comment]
> I'm not sure what _should_ happen here but it likely needs to be fixed in the java plugin. One thought I had is maybe it should use the [`bin/latest-stable`](https://asdf-vm.com/plugins/create.html#optional-scripts) script. Currently rtx doesn't use that since I couldn't find a plugin that used it as a reference. Java doesn't have it either so we'd need to first put one in the plugin for that to be a solution.

The problem with asdf is that it only has a notion of version for a particular plugin. Several plugins are meanwhile provided in various distributions/variants (e.g. Java: Azul, OpenJDK, ... or Python: Anaconda, PyPy, ...) So it rather should support something like <plugin>@<distribution>:<version>. This leads to countless issues with commands like latests etc.

**Comment by jdxcode** [comment]
I'm going to close as it seems this is resolved. The problem we talked about is really in asdf-java if it's anywhere.
