### ISSUE TITLE
legacy file versions not working?

### ISSUE THREAD

**Issue by scullionw** [jdxcode/rtx#243]
**Describe the bug**
rtx isn't using the `.node-version` file in the directory

**To Reproduce**
- have a `.node-version` file, with or without `.tool-versions`
- run `rtx install`
- node still isn't installed

**Expected behavior**
I would expect `rtx install` to install both the tools in tool versions, and also the legacy file versions.

<img width="1442" alt="Screenshot 2023-03-02 at 10 55 31 AM" src="https://user-images.githubusercontent.com/11668344/222394706-08313ee9-c965-4e3d-bddd-22a61a8aa4f8.png">

**Comment by jdxcode** [comment]
This is working as expected: `.tool-versions` overrides values in `.node-versions`. The same is true for `.tool-versions` and `.node-versions` files in parent directories.

Overridden versions do not get installed on `rtx install`.

**Comment by scullionw** [comment]
i don't have anything in `.tool-versions` though

**Comment by jdxcode** [comment]
sorry I looked at the screenshot and noticed the problem: it's nodenv that is complaining about the missing node version, not rtx.

**Comment by scullionw** [comment]
hmm, it is working now (i did switch from using the `| sh` install to `cargo binstall` though)

**Comment by scullionw** [comment]
> sorry I looked at the screenshot and noticed the problem: it's nodenv that is complaining about the missing node version, not rtx.

right, but only because `which node` points to the nodenv shim (instead of the rtx path `/Users/scullionw/.local/share/rtx/installs/node/18.14.1/bin/node`)

**Comment by jdxcode** [comment]
ah now I see what you're saying. Yes this should have worked. If this happens again, it would be useful to see the output of the following:

```
$ RTX_TRACE=1 rtx install
$ RTX_TRACE=1 rtx ls
```

you're correct that `rtx install` should have added the version and then it should have been available here. rtx should be activated in your shell because `rtx doctor` would have complained otherwise.

Your output looks like a bug in rtx to me but I'm not sure what to look at to try to diagnose what went wrong.

**Comment by jdxcode** [comment]
btw the bug is that `rtx install` didn't install node, not that it didn't get added to PATH. If it would have installed it, then it would've shown up in `rtx doctor` (the "toolset" section is blank meaning nothing is installed).

Clearly though `rtx install` exited with no output when it should have attempted to install the missing version.

**Comment by jdxcode** [comment]
I'm going to close unless you start seeing issues again
