### ISSUE TITLE
Command suggestion with invalid .tool-versions format can cause panic

### ISSUE THREAD

**Issue by jordan-brough** [jdxcode/rtx#3]
If you have an invalid `.tool-versions` file like this:
```
ruby: 3.0.5
```
and you run this:
```sh
rtx install
```
then you get this:
```
[WARN] plugin ruby: is not installed. Install it with `rtx plugin add ruby:`
```
Running that command (with the trailing `:`) causes a panic:
```
rtx plugin add ruby:
Downloading ruby-build...
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: src/cli/plugins/install.rs:74

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Abort trap: 6
❌ exit code: 134
```

My bad for not having read the documentation better, but it might be nice to have some
validation warning for invalid `.tool-versions` file formats? Or maybe a nicer error message when an invalid
language (e.g. `ruby:`) is specified?

Not a big deal of course :)

**Comment by jdxcode** [comment]
thanks for this, these are the kinds of rough edges I expect but are hard for me to find on my own since I wouldn't have thought to test for this case. Currently rtx is likely going to be pretty unforgiving since I haven't tried small misconfigurations like this.

Keep these coming as you see them, expect a lot initially.
