### ISSUE TITLE
Paths added by rtx not seen by Sublime Text

### ISSUE THREAD

**Issue by Pilgrim1379** [jdxcode/rtx#325]
**Describe the bug**
Sublime Text can't see any of the paths added by `rtx` hence it complains about not `nodejs` etc. It's as if `rtx` doesn't export `path` after modifying.

**To Reproduce**
Install say `nodejs` with `rtx global nodejs@18`
Start Sublime Text and show console
Then in the console run `import os` followed by `os.environ["PATH"]`
This will show the current path as seen by Sublime Text and the `nodejs` path isn't listed

**Expected behavior**
I expect the path as displayed by `echo $PATH` to be the same for Sublime Text all programs that depend on path settings.

**`rtx doctor` output**

```
rtx version:
  1.23.5 macos-x64 (built 2023-03-13)

shell:
  /usr/local/bin/zsh
  zsh 5.9 (x86_64-apple-darwin21.3.0)

rtx environment variables:
  RTX_SHELL=zsh

settings:
  {"experimental": "false", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:
  /Users/nqa/.tool-versions

plugins:
  direnv   https://github.com/asdf-community/asdf-direnv.git#1a140d6
  elixir   https://github.com/asdf-vm/asdf-elixir.git#1693b35
  elm      https://github.com/asdf-community/asdf-elm.git#df378ce
  erlang   https://github.com/asdf-vm/asdf-erlang.git#0d402e6
  golang   https://github.com/kennyp/asdf-golang.git#f006a12
  java     https://github.com/halcyon/asdf-java.git#ad1f760
  nim      https://github.com/asdf-community/asdf-nim.git#397c14a
  nodejs   https://github.com/asdf-vm/asdf-nodejs.git#644ada3
  python   https://github.com/jdxcode/rtx-python.git#d7ea40b
  ruby     https://github.com/asdf-vm/asdf-ruby.git#3941f47
  zig      https://github.com/cheetah/asdf-zig.git#d88f6db

toolset:
  python@3.11.2, java@temurin-17.0.6+10, erlang@25.3, elixir@1.14.3-otp-25, ruby@3.2.0, elm@0.19.1, golang@1.19.3, nim@1.6.12, zig@0.10.1, direnv@2.32.2, nodejs@18.15.0

No problems found
```

**Additional context**
I have the following in my `.zprofile`:
```
if (( $+commands[rtx] )); then
    eval "$(rtx activate zsh)"
fi
```
I get the full path as expected when I `echo $PATH` from the terminal.
I don't have this issue with `asdf-vm`

**Comment by thepreacher** [comment]
So I have since tried all sorts of tweaks my zsh config. Moving the activation between `.zprofile` and `.zshrc` etc to see if the issue is resolved how ever no luck so far. I therefore swap back to using `asdf` and `sublime text` is able to see the path correctly so it no longer complains about not finding my `lsp` executable anymore.

The one thing I didn't do was use `.profile`. I use `zsh` for my shell so I can't understand why `sublime text` will insist on using `.profile` regardless. With `sublime text` being so popular I'm supprised this is isn't an issue for everybody. I wonder what I'm doing wrong.

So I'm back on `asdf` for now which is a shame because the speed inprovement was very real in my case. I'll find time to go back to `rtx` when I find some time.

**Comment by jdxcode** [comment]
> The one thing I didn't do was use .profile.

Which was the only thing I suggested that you try. You can also use `shims_dir` which will fix this.

**Comment by thepreacher** [comment]
Not using shims or `.profile` yet but starting `subl` from terminal, it now shows all paths same as the terminal does. However the paths set by `rtx` are appended to the end.  

```
'/Users/nqa/.local/bin:/Users/nqa/.cabal/bin:/Users/nqa/.ghcup/bin:/Users/nqa/.local/share/pnpm:/Users/nqa/.cargo/bin:/Users/nqa/go/bin:/Users/nqa/language-servers/zls:/Users/nqa/.local/share/solana/install/active_release/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/nqa/Library/Android/sdk/emulator:/Users/nqa/Library/Android/sdk/platform-tools:/Users/nqa/Library/Android/sdk/tools:/usr/local/opt/ncurses/bin:/usr/local/opt/curl/bin:/usr/local/opt/gettext/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/llvm/bin:/usr/local/bin:/usr/local/sbin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/nqa/.local/share/rtx/installs/nodejs/18.15.0/bin'
```
Therefore say `node` which is installed by some package as dependency takes precedence over `Users/nqa/.local/share/rtx/installs/nodejs/18.15.0/bin'`

Is there anyway to control the odering so that `rtx` paths are prepended instead?

**Comment by thepreacher** [comment]
Thanks for your patience @jdxcode. I added `eval "$(rtx hook-env)"` after activating as you suggested and that has fixed the issue with Sublime Tex for me. In fact the previous breakthrough that I mentioned about the paths been accurate but wrongly ordered was the case only if `subl` is started from the terminal. The gui Sublime Text still couldn't see the additional paths added by `rtx`.

However after adding `eval "$(rtx hook-env)"`, both gui and terminal have the correct path and correctly ordered.

Since  you said 
> I would probably recommend using shims in an IDE environment over activating.
I went ahead and did `rtx reshim` which generated a bunch of links in `.local/share/rtx/shims`. Now all the generated links (excerpt for `pip`, `npm`, `mix` etc had this pattern `<executable> -> /usr/local/bin/rtx*`. 

1. Can you explain the links all mapping to `/usr/local/bin/rtx*` since `rtx` is itself a binary. 
2. With Sublime Text working without the `shims`, do you still recommend that I keep the `shims`?

Regarding the first question please feel free to point me to an existing answer if there's one.

**Comment by jdxcode** [comment]
this is now documented in the readme (see IDE integration)
