### ISSUE TITLE
.tool-versions takes precedence over .rtx.toml and .config/rtx/config.toml

### ISSUE THREAD

**Issue by yssource** [jdxcode/rtx#337]
`rtx doctor`
```
config files:
  /home/jimmy/.config/rtx/config.toml
  /home/jimmy/.tool-versions
```

/home/jimmy/.config/rtx/config.toml

```
[settings]
experimental = true
asdf_compat = true
missing_runtime_behavior = "prompt"
verbose = true
shims_dir = ".shims"

[tools]
java = "openjdk-20"
```
```
➜ ls -al ~/.local/share/rtx/installs/java/openjdk-20/
drwxr-xr-x    - jimmy 17 Mar 00:18 bin
drwxr-xr-x    - jimmy 17 Mar 00:18 conf
drwxr-xr-x    - jimmy 17 Mar 00:18 include
drwxr-xr-x    - jimmy 17 Mar 00:18 jmods
drwxr-xr-x    - jimmy 17 Mar 00:18 legal
drwxr-xr-x    - jimmy 17 Mar 00:18 lib
.rw-r--r-- 1.2k jimmy 11 Feb 03:44 release
```

~/.tool-versions
`java adopt-openjdk-11.0.7+10`

```
✗ ls -al ~/.asdf/installs/java/adopt-openjdk-11.0.7+10/
drwxr-xr-x    - jimmy 15 Apr  2020 bin
drwxr-xr-x    - jimmy 15 Apr  2020 conf
drwxr-xr-x    - jimmy 15 Apr  2020 include
drwxr-xr-x    - jimmy 15 Apr  2020 jmods
drwxr-xr-x    - jimmy 15 Apr  2020 legal
drwxr-xr-x    - jimmy 15 Apr  2020 lib
drwxr-xr-x    - jimmy 15 Apr  2020 man
.rw-r--r-- 1.2k jimmy 15 Apr  2020 release
```

Error report:

```
rtx java not found
rtx java@adopt-openjdk-11.0.7+10 not installed
```

**Comment by jdxcode** [comment]
If you're in a subdirectory of `$HOME`, this is expected behavior. `~/.tool-versions` is just another "local" config file and local files take precedence over global ones.

However if you're somewhere else like `/tmp`, then this is an issue because `~/.tool-versions` _shouldn't_ be considered a "global" config file. You can force this behavior by setting: `RTX_CONFIG_FILE=/Users/jdx/.config/rtx/config.toml`.

This should also be the case if `RTX_USE_TOML=1`, which isn't the case currently but I'm going to put a patch in for that case.

**Comment by yssource** [comment]
The patch fixed the problem, thanks for your so quickly response.
