### ISSUE TITLE
asdf plugin script looking for command asdf

### ISSUE THREAD

**Issue by rbauduin** [jdxcode/rtx#435]
I installed dotnet-core with rtx (https://github.com/emersonsoares/asdf-dotnet-core) and it provides a script to set `DOTNET_ROOT`. The script provided by the plugin invokes `asdf which dotnet`, which makes it unusable as is with rtx. Maybe aliasing rtx to asdf would make sense for such a case?

**Comment by jdxcode** [comment]
can't you just do `ln -s $(which rtx) ~/rtx`?

**Comment by rbauduin** [comment]
> can't you just do `ln -s $(which rtx) ~/bin/asdf`?

Yes, it's not a big problem. It was just a suggestion to possibly smooth the experience. It could possibly set up an alias when running `eval "$(rtx execute bash)", but I understand it might have some other implications. Feel free to close this issue of it's not worth further consideration.
Thanks for the mention of `exec-env`, I'm just starting with rtx and never used asdf and wasn't aware of it.

**Comment by jdxcode** [comment]
So an alias won't be helpful here. Shell aliases _only_ get used when within the interactive prompt, scripts don't have a way to call them. We _do_ set up an asdf wrapper inside of plugin scripts, but that doesn't apply here since this is a script external to rtx.

One solution would be to install an "asdf" binary globally in PATH, but that would conflict with people that use asdf and rtx at the same time (which happens).

Anyways, I know you offered to close this but I figured I'd give you some insight into this if you were curious. The real answer is for this to use an exec-env script which will also make it so you don't need the extra script to be installed when setting it up.

**Comment by jdxcode** [comment]
btw you could probably literally just copy the bash setup script to bin/exec-env and it would fix this for you.

Though I'm not sure how well that PROMPT_COMMAND stuff will work so it might be good to remove it.

**Comment by rbauduin** [comment]
Thanks for the explanations.  For reference, if someone in the future stumbles on this discussion, I got it working by copying the script to `~/.local/share/rtx/plugins/dotnet-core/bin/exec-env` and adapting it as such:
- replace the call to `asdf which` by a call to `rtx which`
- call at the end of the script the bash function setting DOTNET_ROOT
- cleanup: remove the PROMPT_COMMAND as you suggested and the then unused function

This is what worked for me:

```
asdf_update_dotnet_home() {
  local dotnet_path
  dotnet_path="$(rtx which dotnet 2> /dev/null  )"
  if [[ -n "${dotnet_path}" ]]; then
    export DOTNET_ROOT
    DOTNET_ROOT="$(dirname "$(realpath "${dotnet_path}")")"
  fi
}
asdf_update_dotnet_home
```

**Comment by jdxcode** [comment]
you should submit this as a PR to the plugin

**Comment by rbauduin** [comment]
Yes, I'm looking at it. I don't know yet how to support multiple shells (bash, fish, zsh) with one exec-env though (as the repo includes scripts for each of these shells, I suppose a PR supporting all 3 shells would be easier to accept for the maintainer).

**Comment by jdxcode** [comment]
you only need bash since that's all that asdf and rtx use under the hood

**Comment by jdxcode** [comment]
closing in favor of the plugin PR
