### ISSUE TITLE
rtx reshim should NOT delete everything in the target folder

### ISSUE THREAD

**Issue by eugenesvk** [jdxcode/rtx#478]
**Describe the bug**
`rtx reshim` deletes the `shims_dir` folder content

**To Reproduce**
- set in your config
```toml
experimental	= true              	# |false|	enable experimental features such as shims
shims_dir   	= '~/.local/bin/rtx'	# ||     	directory where shims are stored
```
- create a file in `~/.local/bin/rtx`
- run `rtx reshim`
- your file is gone

**Expected behavior**
Rtx should __only__ touch the files that __it__ __generates__

<details>
  <summary>rtx doctor output</summary>

```
~ ❯ rtx doctor
rtx version:
  1.27.12 macos-x64 (cc5b77f 2023-04-05)

build:
  Target: x86_64-apple-darwin
  Features: BREW
  Built: Wed, 05 Apr 2023 20:19:35 +0000
  Rust Version: rustc 1.68.0 (2c8cc3432 2023-03-06)
  Profile: release

shell:
  /opt/local/bin/fish
  fish, version 3.6.1

rtx environment variables:
  (none)

settings:
  {"experimental": "true", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "trusted_config_paths": "[]", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "shims_dir": "~/.local/bin/rtx/shim", "raw": "false"}

config files:
  ~/.config/rtx/config.toml
  ~/.tool-versions

plugins:
  direnv   https://github.com/asdf-community/asdf-direnv.git#e3622e6
  nodejs   https://github.com/asdf-vm/asdf-nodejs.git#644ada3

toolset:
  nodejs@18

No problems found
```
</details>

**Additional context**
I had a few other rtx-related binaries in that folder that I thought would be nice to colocate and have a single path entry, but now they're poof

**Comment by jdxcode** [comment]
I can see how this might be frustrating but the alternative is to do a bunch of bookkeeping I would very much like to avoid since it's more to manage, more places for bugs to crop up.

This might just require some documentation that this isn't intended to be used for other bins.

**Comment by eugenesvk** [comment]
Well, one destructive bug has already cropped up :)
Could rtx at least print a list of files it's planning to delete and ask for confirmation with a default no and some `--auto-delete` flag for the brave ones?


btw, I'm only doing shims to solve the Sublime Text issue, and you mentioned it's better to use paths in shims: why is it better? Maybe I could go to the other alternative instead and forget this bad experiment :)

**Comment by jdxcode** [comment]
> Could rtx at least print a list of files it's planning to delete and ask for confirmation with a default no and some --auto-delete flag for the brave ones?

no, because the implication is that you're using this directory for something _other_ than shims which is not a supported use-case. It's also not easy since there are many places reshimming is performed/will be performed. Why are you doing that instead of some other directory like `~/.local/bin` or `~/.local/share/rtx/bin`?

> mentioned it's better to use paths in shims

Where have I said this? The readme has a section on IDEs where I say that you _should_ use shims for IDEs.

**Comment by jdxcode** [comment]
OK I see where you and I are missing each other now. I missed that you were using `~/.local/bin`—which is a horrible idea but not one I would fault you for trying since the docs are not clear on this, especially after reading them again.

The default directory is going to be `~/.local/share/rtx/shims`—which is the one that the vast majority of people will use I suspect. That is probably not the case today as it's experimental and setting that directory is a heuristic for enabling this. I think once that directory is set this won't be as much of an issue since people won't be forced to select a directory themselves.

You misunderstood my suggestion about using `~/.local/bin`, but that was a result of me not understanding you weren't using a specific directory. I was saying you should use those directories for *non*-shim bins.

Anyways, shims should have a dedicated directory. I think making this behavior the default and setting it to `~/.local/share/rtx/shims` will help people avoid this issue. This directory matches what asdf uses and I don't think asdf even allows modifying the directory which might be another way we could mitigate this problem.

**Comment by jdxcode** [comment]
In other words, I think making this directory configurable may have been a mistake in the first place. If it was hardcoded to $RTX_DATA_DIR/shims like asdf this likely wouldn't be a problem. That was how I assumed people would use it even if it _was_ configurable, but you've shown me that isn't going to necessarily be how people will use it.

**Comment by eugenesvk** [comment]
I agree that without mitigation it's better not to have this configurable, even the docs wouldn't saved me as it's just not something I would even expect to check the docs for since I assume it behaves just like all the other shimming solutions I've used behave (for what it's worth, I've just checked asdf, and it doesn't delete extra files in its shim folder ~/.asdf/shims on reshim command)
