### ISSUE TITLE
Docs: Provide workflow oriented examples

### ISSUE THREAD

**Issue by juljaeg** [jdxcode/rtx#513]
Hi,

I really like rtx but find it quite complicated to remember each and every command and its purpose. Also the CLI does not seem stable. By CLI I really mean the interface - commands are changing a lot (looking at you `rtx global`). I think it would be really helpful to provide some workflow orientied help in the README.

Examples:
- Installing a global tool by pinning, installing and adding it to the global config file
- Same for local tools
- How to install the necessary tools after cloning a new repository
- Updating a plugin & and the installed tool, also updating the corresponding entry in local and/or global config

This scenarios look quite complicated when only looking at the interface with this amount of commands and options. I think it would be helpful to either have some top level commands and some porcelain related like Git does.

**Comment by jdxcode** [comment]
This is the purpose behind the "common commands" section: https://github.com/jdxcode/rtx#common-commands Upgrades are missing but that's because `rtx upgrade` hasn't been implemented yet.

I don't believe you're correct that "commands are changing a lot". `rtx use` was added and `rtx global|local` have been made hidden, but otherwise they didn't change at all, you can still use local|global and they work the same as before. I am going to make breaking changes to commands up until the Calver release as documented, but most of that are things like how I slightly changed the output of `rtx ls` which is only an issue for people that script the command.

**Comment by jdxcode** [comment]
That said, once rtx is activated, `rtx use` might be the only command that probably 50-75% of users ever would need to ever run.

**Comment by juljaeg** [comment]
Can't believe I oversaw this! Thank you for the hint. I just noticed different behaviour for rtx global and local and saw multiple changes related to cli commands. By no means this was meant to offense - I really like using rtx but do only sporadicly check the changelogs 😄
