### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by francescortiz** [jdxcode/rtx#544]
Searching for "rtx" gives about 163,000,000 results in google, almost all of them most likely related to Nvidia graphics cards. When I search for this project I have to add "asdf" to the search string in order to have the information I look for. This makes the project harder to grasp when you look quickly for how to do specific things.

PS: Regarding the name, I don't care much, but if you want a suggestion that comes to my mind it could be rtx-asdf or asdf-rtx because it is asdf compatible.

**Comment by jdxcode** [comment]
this project has transcended being a simple asdf replacement. I don't see how rtx-asdf would change anything since as you say googling "rtx asdf" will already point you directly towards this project.

That said I do wish I would've spent more than 5 minutes coming up with a name and chose one that didn't conflict with nvidia's product. I very much like that it's 3 characters that doesn't seem to conflict with any CLIs though.

At least right now, I don't have the appetite for going through a rename though. I think that Google will improve over time and with context know if you're talking about nvidia or this project. I think if you just google "rtx" it might not give you the right answer, but if you google "rtx python" it probably always will offer the right thing. So I'm not sure how big of a problem this is.

**Comment by astrojuanlu** [comment]
In the end, the project was renamed 😄 https://mise.jdx.dev/rtx.html
