### ISSUE TITLE
Missing asdf lib required by some plugins

### ISSUE THREAD

**Issue by nrjais** [jdxcode/rtx#59]
Tried to install java but which failed with
```
rtx: Installing runtime: java@latest
/Users/neeraj/.local/share/rtx/plugins/java/bin/install: line 3: /Users/neeraj/.asdf/lib/utils.bash: No such file or directory
Unknown release: latest
rtx: error command ["/Users/neeraj/.local/share/rtx/plugins/java/bin/install"] exited with code 1
rtx: Run with RTX_DEBUG=1 for more information.
```

This seems like some plugin need `https://github.com/asdf-vm/asdf/tree/master/lib`, Should I install asdf also to make it work.

Cat rtx setup these files automatically on first install?

**Comment by jdxcode** [comment]
https://github.com/jdxcode/rtx/issues/2

**Comment by jdxcode** [comment]
you're seeing 2 errors here, the first is a red herring that #2 talks about, it doesn't cause any real issues. The second one is also in #2 and likely needs to be fixed by asdf-java. I (or one of us) should probably reach out to asdf-java and see if they'd be open to having a default java type. You can install java with `rtx install java@openjdk`

**Comment by jdxcode** [comment]
to answer your question though, I don't think it makes sense to include all of asdf inside of rtx for several reasons. We should find a different solution.
