### ISSUE TITLE
When exactly should rtx be hooked into in a shell

### ISSUE THREAD

**Issue by eugenesvk** [jdxcode/rtx#69]
I've updated rtx to work with this great Python-powered, cross-platform, Unix-gazing shell https://github.com/xonsh/xonsh (will send a PR eventually) and when converting the hook functions noticed differences between fish/bash, and then got a bit confused, so need some clarification

Your Readme suggests that there should only be two hook events
  - on shell launch (makes sense, before any `cd` you still need to check the cwd)
  - on `cd` (makes sense, every new cwd can have a different environment)

> rtx installs as a shell extension (e.g. rtx activate -s zsh) that sets the PATH environment variable to point your shell to the correct runtime binaries. When you cd into a directory containing a .tool-versions file, rtx will automatically activate the correct versions.
> Every time your prompt starts it will call rtx hook-env to fetch new environment variables. This should be very fast and it exits early if the the directory wasn't changed or the .tool-version files haven't been updated. On my machine this takes 1-2ms even if it doesn't exit early.

But then `zsh` has two hooks in `activate` functions
  - `chpwd_functions` on `cd`
  - `precmd_functions` before every command
  - no 3rd hook on shell launch, but I guess you don't need to do anything on shell launch if you don't execute any commands?

Bash has one in an `activate` function
  - `if ! [[ "${PROMPT_COMMAND:-}" =~ _rtx_hook ]]` on every command?
  - also no hook on launch?

Fish is a bit more complicated
  - `fish_prompt` on every prompt, but within and then an extra check for `cd` depending on user config
  - `fish_preexec` before every command, but also depends on user config
The hook on launch comes from `fish_prompt`, I guess

Xonsh allows more granularity than the shells above (before/after prompt, before/after command, on `cd`), so I'm just trying to understand what the minimum viable set of hooks should be

So a few questions:
  - why do you need to hook every single command execution, is `cd`+`launch` from the Readme not enough?
  - why do you need any hooks on `cd` if you already hook into every command?
  - why do you need to update on every prompt (fish) even after launch without any commands/`cd` (so I guess every hit of Enter on an emtpy line updates?)

Thanks for any clarification!

**Comment by jdxcode** [comment]
this is a good question, I've copied this code almost verbatim from [direnv](https://github.com/direnv/direnv/blob/master/internal/cmd/shell_bash.go) btw, because it's basically doing the same thing and I wanted to get it right.

We check every shell execution because we need to check if `.tool-versions` change when there wasn't a directory change. Otherwise this wouldn't work:

```
$ echo "nodejs 18.0.0" >> .tool-versions
$ node -v
18.0.0
$ echo "nodejs 16.0.0" >> .tool-versions
$ node -v
16.0.0
```

If the user had to leave the directory and enter it again that would be very annoying.

**Comment by eugenesvk** [comment]
> If the user had to leave the directory and enter it again that would be very annoying

Sure it would be! Though there could be (likely pointless :) given how fast rtx is pointless) alternatives:
  - hook only into empty commands, so Enter would refresh
  - have `rtx` auto-refresh without args (or have less friendly `rtx refresh`/`rehash`, or dare I say `reshim`)
  - hook into subset of commands that mention the `.tool-versions` (cumbersome and doesn't guarantee much)

But that's just an aside, my __main question__ remains: why do you need any hooks on `cd` if you already hook into every command? Would it be fine to just have this one hook like in bash?

Then the https://github.com/jdxcode/rtx#how-it-works section could be simplified to say that the refresh happens before every single command so everything is always fresh!

**Comment by jdxcode** [comment]
We can make `hook-env` faster. Last I checked it was so fast it didn't warrant it. Well, at least if the cache fresh. Once per day each plugin will have to read each legacy file and that isn't particularly fast but since it's cached I don't think it's likely to be a problem. It's also parallelized (at least it should be). I think if we want to improve the performance of people's shells we should do what we can that wouldn't require degrading the experience and requiring a special workflow to adopt new config. Keep in mind that you would need to do this in every shell session, so if you have a terminal window with 5 tabs in the same directory (as I often do), you'll need to repeat that workflow for each and every one.

> But that's just an aside, my main question remains: why do you need any hooks on cd if you already hook into every command? Would it be fine to just have this one hook like in bash?

Maybe you could tell me if you figure out why :) Like I said I just copied this from direnv so it's definitely cargo-cult. I know in fish shell you can change directory with alt+arrow keys and that _doesn't_ show a new prompt, just modifies the existing (that's why there are those config settings in fish). I can't speak for other shells. Really though, I don't know, perhaps we could remove it, but I suspect direnv has a good reason for doing it this way.

In terms of the docs, I think you need to remember that people like you aren't really the audience I'm talking to—that want to know precisely how it works. I want to make sure what I say is easy enough to understand for a new developer since these kind of tools I find new developers get really stuck on. So when I say "When you cd into a directory containing a .tool-versions file, rtx will automatically activate the correct versions.", that's definitely accurate, and I think it encapsulates the expected behavior in a way the user expects. If I simplified this to say "every time your shell starts it fetches new versions" that's technically more accurate, and simpler, but I think to someone that doesn't even understand what they would use rtx for, they miss the point of why they want it to run in the first place. I know this is in the "how it works" section, but I'm actually still thinking of the n00b here.

Of course I also want to make sure that what I say is correct and that people like you also are able to get more details about the precise mechanics, which is what the next paragraph is for:

> _Every time your prompt starts_ it will call `rtx hook-env` to fetch new environment variables. This should be very fast and it exits early if the the directory wasn't changed or the .tool-version files haven't been updated.

Anyways, this isn't to say I think the docs are perfect, I know they're not. I'm just explaining why they aren't simplified to the extent as you say when that would be technically accurate.

If we were able to remove the hook on cd, I wouldn't actually change that section I don't think.

**Comment by eugenesvk** [comment]
> we want to improve the performance of people's shells we should do what we can that wouldn't require degrading the experience and requiring a special workflow to adopt new config.

Sure, sounds like a good plan! I'm definitly fine with an unnoticeable 1-2ms delay on every command and not worrying about any manual refreshes!


> Maybe you could tell me if you figure out why :)

Maybe :) Though thinking a bit more on the fish examle tells me there is no duplication:

>   I know in fish shell you can change directory with alt+arrow keys and that doesn't show a new prompt, just modifies the existing (that's why there are those config settings in fish).

Yes, and without the arrow changes fish only has one `fish_prompt` hook, the hook on every command is only needed to allow delaying the updates until after all the arrow changes happen (otherwise these updates happen on every single arrow `cd`)
Think this clarifies it a bit, I'll go with the fish option of calling `rtx` once per prompt drawing and see if any arrow-based dir changes fail to trigger
Thanks!

> which is what the next paragraph is for:

>> Every time your prompt starts 

Sure, I just read it as `your shell starts`, not as `your prompt is redrawn`, but that's fine, I think my confusion stemed more from the combo of docs+code
