### ISSUE TITLE
document python dependencies

### ISSUE THREAD

**Issue by jdxcode** [jdxcode/rtx#826]
[this doc](https://github.com/jdxcode/rtx/blob/main/docs/python.md) should include a link to pyenv's instructions on setting up the environment. It should also explain how rtx uses python-build under the hood (and that python-build is part of pyenv)

**Comment by BuildBackBuehler** [comment]
This is..."serendipity" at its finest, hah. Just realized how I have been missing out on M1 optimizations w/ Python, or at least I presume so. A post-all-nighter reading of the Python.md doesn't quite bash you in the head with the answer(s) I'm looking for 😂. The M1 Optimizations I'm speaking of are apart of "Miniforge" – which relies on Conda...

But I'd of course like to rely on rtx's pyenv-based structure. Figure its less room for error with updates and such. I started going through the nuts & bolts of rtx's core python install and it looks as though patching pyenv may enable one to use miniforge w/o a conda/mamba .env? 

I couldn't find any asdf miniforge info, figured that was my best shot at figuring this out. This is all I've found and they do opt for enveption-ing Conda + Pyenv. 

https://www.fredlich.com/works/installing-tensorflow-on-m1-with-pyenv
https://medium.com/@glen.yu/installing-tensorflow-on-apple-m1-pro-using-pyenv-7a7dec40f7c6

Though I have a feeling the information I'm relying on is outdated because its so rare to run into a non-native package. 

In which case, I suppose one can just rely on the rtx python build, install rtx-poetry/pip to manage python packs and go about one's day? 

One caveat is that the tensorflow/metal-based optimizations aren't rolled into the pypack managers by default, which of course would be a great add-on to the documentation 😂. Happy to provide more issues that have impacted me but I don't think I could eloquently write out how to resolve 'em.
